# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  # AccountRoutes Model.
  class AccountRoutes < BaseModel
    # TODO: Write general description for this method
    # @return [List of Object]
    attr_accessor :data

    # TODO: Write general description for this method
    # @return [Object]
    attr_accessor :links

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['data'] = 'data'
      @_hash['links'] = 'links'
      @_hash
    end

    def initialize(data = nil,
                   links = nil)
      @data = data
      @links = links
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      data = hash['data']
      links = hash['links']

      # Create object from extracted values.
      AccountRoutes.new(data,
                        links)
    end
  end
end
