# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  # Attributes62 Model.
  class Attributes62 < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :malias

    # TODO: Write general description for this method
    # @return [RouteTypeEnum]
    attr_accessor :route_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['malias'] = 'alias'
      @_hash['route_type'] = 'route_type'
      @_hash['value'] = 'value'
      @_hash
    end

    def initialize(malias = nil,
                   route_type = RouteTypeEnum::SIPREG,
                   value = nil)
      @malias = malias
      @route_type = route_type
      @value = value
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      malias = hash['alias']
      route_type = hash['route_type'] ||= RouteTypeEnum::SIPREG
      value = hash['value']

      # Create object from extracted values.
      Attributes62.new(malias,
                       route_type,
                       value)
    end
  end
end
