# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  # Attributes28 Model.
  class Attributes28 < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :malias

    # TODO: Write general description for this method
    # @return [Boolean]
    attr_accessor :cnam_lookups_enabled

    # TODO: Write general description for this method
    # @return [NumberTypeEnum]
    attr_accessor :number_type

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :rate_center

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :state

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :value

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['malias'] = 'alias'
      @_hash['cnam_lookups_enabled'] = 'cnam_lookups_enabled'
      @_hash['number_type'] = 'number_type'
      @_hash['rate_center'] = 'rate_center'
      @_hash['state'] = 'state'
      @_hash['value'] = 'value'
      @_hash
    end

    def initialize(malias = nil,
                   cnam_lookups_enabled = nil,
                   number_type = nil,
                   rate_center = nil,
                   state = nil,
                   value = nil)
      @malias = malias
      @cnam_lookups_enabled = cnam_lookups_enabled
      @number_type = number_type
      @rate_center = rate_center
      @state = state
      @value = value
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      malias = hash['alias']
      cnam_lookups_enabled = hash['cnam_lookups_enabled']
      number_type = hash['number_type']
      rate_center = hash['rate_center']
      state = hash['state']
      value = hash['value']

      # Create object from extracted values.
      Attributes28.new(malias,
                       cnam_lookups_enabled,
                       number_type,
                       rate_center,
                       state,
                       value)
    end
  end
end
