# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  # Data Model.
  class Data < BaseModel
    # TODO: Write general description for this method
    # @return [Attributes]
    attr_accessor :attributes

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['attributes'] = 'attributes'
      @_hash['id'] = 'id'
      @_hash['type'] = 'type'
      @_hash
    end

    def initialize(attributes = nil,
                   id = nil,
                   type = 'message')
      @attributes = attributes
      @id = id
      @type = type
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      attributes = Attributes.from_hash(hash['attributes']) if
        hash['attributes']
      id = hash['id']
      type = hash['type'] ||= 'message'

      # Create object from extracted values.
      Data.new(attributes,
               id,
               type)
    end
  end
end
