# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module FlowrouteNumbersAndMessaging
  # DeliveryReceipt Model.
  class DeliveryReceipt < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :level

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :status

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :status_code

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :status_code_description

    # TODO: Write general description for this method
    # @return [DateTime]
    attr_accessor :timestamp

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['level'] = 'level'
      @_hash['status'] = 'status'
      @_hash['status_code'] = 'status_code'
      @_hash['status_code_description'] = 'status_code_description'
      @_hash['timestamp'] = 'timestamp'
      @_hash
    end

    def initialize(level = nil,
                   status = nil,
                   status_code = nil,
                   status_code_description = nil,
                   timestamp = nil)
      @level = level
      @status = status
      @status_code = status_code
      @status_code_description = status_code_description
      @timestamp = timestamp
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      level = hash['level']
      status = hash['status']
      status_code = hash['status_code']
      status_code_description = hash['status_code_description']
      timestamp = DateTime.rfc3339(hash['timestamp']) if hash['timestamp']

      # Create object from extracted values.
      DeliveryReceipt.new(level,
                          status,
                          status_code,
                          status_code_description,
                          timestamp)
    end
  end
end
