# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  # Error84 Model.
  class Error84 < BaseModel
    # TODO: Write general description for this method
    # @return [List of Error1]
    attr_accessor :errors

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['errors'] = 'errors'
      @_hash
    end

    def initialize(errors = nil)
      @errors = errors
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      errors = nil
      unless hash['errors'].nil?
        errors = []
        hash['errors'].each do |structure|
          errors << (Error1.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      Error84.new(errors)
    end
  end
end
