# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  # Error1 Model.
  class Error1 < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :id

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :status

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :detail

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :title

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['status'] = 'status'
      @_hash['detail'] = 'detail'
      @_hash['title'] = 'title'
      @_hash
    end

    def initialize(id = nil,
                   status = nil,
                   detail = nil,
                   title = nil)
      @id = id
      @status = status
      @detail = detail
      @title = title
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash['id']
      status = hash['status']
      detail = hash['detail']
      title = hash['title']

      # Create object from extracted values.
      Error1.new(id,
                 status,
                 detail,
                 title)
    end
  end
end
