# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  # Links Model.
  class Links < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :mself

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['mself'] = 'self'
      @_hash
    end

    def initialize(mself = nil)
      @mself = mself
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      mself = hash['self']

      # Create object from extracted values.
      Links.new(mself)
    end
  end
end
