# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  # MessageType.
  class MessageTypeEnum
    MESSAGE_TYPE_ENUM = [
      # TODO: Write general description for LONGCODE
      LONGCODE = 'longcode'.freeze,

      # TODO: Write general description for TOLLFREE
      TOLLFREE = 'toll-free'.freeze
    ].freeze
  end
end
