# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  # NewRoute Model.
  class NewRoute < BaseModel
    # TODO: Write general description for this method
    # @return [Data61]
    attr_accessor :data

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['data'] = 'data'
      @_hash
    end

    def initialize(data = nil)
      @data = data
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      data = Data61.from_hash(hash['data']) if hash['data']

      # Create object from extracted values.
      NewRoute.new(data)
    end
  end
end
