# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  # NumberType.
  class NumberTypeEnum
    NUMBER_TYPE_ENUM = [
      # TODO: Write general description for STANDARD
      STANDARD = 'standard'.freeze,

      # TODO: Write general description for TOLLFREE
      TOLLFREE = 'tollfree'.freeze,

      # TODO: Write general description for INUM
      INUM = 'inum'.freeze
    ].freeze
  end
end
