# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  # Number26 Model.
  class Number26 < BaseModel
    # TODO: Write general description for this method
    # @return [Data27]
    attr_accessor :data

    # TODO: Write general description for this method
    # @return [List of Object]
    attr_accessor :included

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['data'] = 'data'
      @_hash['included'] = 'included'
      @_hash
    end

    def initialize(data = nil,
                   included = nil)
      @data = data
      @included = included
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      data = Data27.from_hash(hash['data']) if hash['data']
      included = hash['included']

      # Create object from extracted values.
      Number26.new(data,
                   included)
    end
  end
end
