# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  # RouteType.
  class RouteTypeEnum
    ROUTE_TYPE_ENUM = [
      # TODO: Write general description for SIPREG
      SIPREG = 'sip-reg'.freeze,

      # TODO: Write general description for HOST
      HOST = 'host'.freeze,

      # TODO: Write general description for URI
      URI = 'uri'.freeze,

      # TODO: Write general description for NUMBER
      NUMBER = 'number'.freeze
    ].freeze
  end
end
