# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  #  flowroute_numbers_and_messaging client class.
  class FlowrouteNumbersAndMessagingClient
    # Singleton access to messages controller.
    # @return [MessagesController] Returns the controller instance.
    def messages
      MessagesController.instance
    end

    # Singleton access to numbers controller.
    # @return [NumbersController] Returns the controller instance.
    def numbers
      NumbersController.instance
    end

    # Singleton access to routes controller.
    # @return [RoutesController] Returns the controller instance.
    def routes
      RoutesController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end

    # Initializer with authentication and configuration parameters.
    def initialize(basic_auth_user_name: nil, basic_auth_password: nil)
      Configuration.basic_auth_user_name = basic_auth_user_name if
        basic_auth_user_name
      Configuration.basic_auth_password = basic_auth_password if
        basic_auth_password
    end
  end
end
