# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module FlowrouteNumbersAndMessaging
  # RoutesController
  class CNAMController < BaseController
    @instance = CNAMController.new

    class << self
      attr_accessor :instance
    end

    def instance
      self.class.instance
    end

    # Returns a list of your CNAM Records.
    # @param [Integer] limit Optional parameter: Limits the number of records to
    # retrieve. A maximum of 200 items can be retrieved.
    # @param [Integer] offset Optional parameter: Offsets the list of records by
    # your specified value. For example, if you have 4 records and you
    # entered 1 as your offset value, then only 3 of your records will be
    # displayed in the response.
    # @return void response from the API call
    def list_cnams(limit = 10,
                   offset = 0,
                   is_approved=nil)
      # Prepare query url.
      _query_builder = Configuration.base_uri.dup
      _query_builder << '/v2/cnams'
      _query_builder = APIHelper.append_url_with_query_parameters(
        _query_builder,
        {
          'limit' => limit,
          'offset' => offset
        },
        array_serialization: Configuration.array_serialization
      )

      if is_approved != nil
        _query_builder = APIHelper.append_url_with_query_parameters(
          _query_builder,
          {
            'is_approved' => is_approved 
          },
          array_serialization: Configuration.array_serialization
        )
      end

      _query_url = APIHelper.clean_url _query_builder

      # Prepare and execute HttpRequest.
      _request = @http_client.get(
        _query_url
      )
      BasicAuth.apply(_request)
      _context = execute_request(_request)

      # Validate response against endpoint and global error codes.
      if _context.response.status_code == 401
        raise APIException.new(
          'Unauthorized',
          _context
        )
      elsif _context.response.status_code == 404
        raise APIException.new(
          'Not Found',
          _context
        )
      end
      validate_response(_context)
      
      # Return appropriate response type.
      decoded = APIHelper.json_deserialize(_context.response.raw_body) unless
        _context.response.raw_body.nil? ||
        _context.response.raw_body.to_s.strip.empty?
      decoded
    end

    def cnam_details(cnam_id)
      # Prepare query url.
      _query_builder = Configuration.base_uri.dup
      _query_builder << '/v2/cnams/{cnam_id}'
      _query_builder = APIHelper.append_url_with_template_parameters(
        _query_builder,
        'cnam_id' => cnam_id
      )
      _query_url = APIHelper.clean_url _query_builder

      # Prepare and execute HttpRequest.
      _request = @http_client.get(
        _query_url
      )
      BasicAuth.apply(_request)
      _context = execute_request(_request)

      # Validate response against endpoint and global error codes.
      if _context.response.status_code == 401
        raise APIException.new(
          'Unauthorized',
          _context
        )
      elsif _context.response.status_code == 404
        raise APIException.new(
          'Not Found',
          _context
        )
      end
      validate_response(_context)
      
      # Return appropriate response type.
      decoded = APIHelper.json_deserialize(_context.response.raw_body) unless
        _context.response.raw_body.nil? ||
        _context.response.raw_body.to_s.strip.empty?
      decoded
    end

    def associate(did_id, cnam_id)
      # Prepare query url.
      _query_builder = Configuration.base_uri.dup
      _query_builder << '/v2/numbers/{did_id}/relationships/cnam/{cnam_id}'
      _query_builder = APIHelper.append_url_with_template_parameters(
        _query_builder,
        'did_id' => did_id,
        'cnam_id' => cnam_id
      )

      _query_url = APIHelper.clean_url _query_builder

      # Prepare and execute HttpRequest.
      _request = @http_client.patch(
        _query_url
      )

      BasicAuth.apply(_request)
      _context = execute_request(_request)

      # Validate response against endpoint and global error codes.
      if _context.response.status_code == 401
        raise APIException.new(
          'Unauthorized',
          _context
        )
      elsif _context.response.status_code == 404
        raise APIException.new(
          'Not Found',
          _context
        )
      end
      validate_response(_context)
      
      # Return appropriate response type.
      decoded = APIHelper.json_deserialize(_context.response.raw_body) unless
        _context.response.raw_body.nil? ||
        _context.response.raw_body.to_s.strip.empty?
      decoded
    end

    def create(cnam_string)
      # Prepare query url.
      _query_builder = Configuration.base_uri.dup
      _query_builder << '/v2/cnams'
      _query_url = APIHelper.clean_url _query_builder

      cnam_record = {"value" => cnam_string}

      # Prepare and execute HttpRequest.
      _request = @http_client.post(
        _query_url,
        parameters: cnam_record
      )

      BasicAuth.apply(_request)
      _context = execute_request(_request)

      # Validate response against endpoint and global error codes.
      if _context.response.status_code == 401
        raise APIException.new(
          'Unauthorized',
          _context
        )
      elsif _context.response.status_code == 404
        raise APIException.new(
          'Not Found',
          _context
        )
      end
      validate_response(_context)
      
      # Return appropriate response type.
      decoded = APIHelper.json_deserialize(_context.response.raw_body) unless
        _context.response.raw_body.nil? ||
        _context.response.raw_body.to_s.strip.empty?
      decoded
    end

    def unassociate(did_id)
      # Prepare query url.
      _query_builder = Configuration.base_uri.dup
      _query_builder << '/v2/numbers/{did_id}/relationships/cnam'
      _query_builder = APIHelper.append_url_with_template_parameters(
        _query_builder,
        'did_id' => did_id
      )

      _query_url = APIHelper.clean_url _query_builder

      # Prepare and execute HttpRequest.
      _request = @http_client.delete(
        _query_url
      )

      BasicAuth.apply(_request)
      _context = execute_request(_request)

      # Validate response against endpoint and global error codes.
      if _context.response.status_code == 401
        raise APIException.new(
          'Unauthorized',
          _context
        )
      elsif _context.response.status_code == 404
        raise APIException.new(
          'Not Found',
          _context
        )
      end
      validate_response(_context)
      
      # Return appropriate response type.
      decoded = APIHelper.json_deserialize(_context.response.raw_body) unless
        _context.response.raw_body.nil? ||
        _context.response.raw_body.to_s.strip.empty?
      decoded
    end

    def delete_record(cnam_id)
      # Prepare query url.
      _query_builder = Configuration.base_uri.dup
      _query_builder << '/v2/cnams/{cnam_id}'
      _query_builder = APIHelper.append_url_with_template_parameters(
        _query_builder,
        'cnam_id' => cnam_id
      )

      _query_url = APIHelper.clean_url _query_builder

      # Prepare and execute HttpRequest.
      _request = @http_client.delete(
        _query_url
      )

      BasicAuth.apply(_request)
      _context = execute_request(_request)

      # Validate response against endpoint and global error codes.
      if _context.response.status_code == 401
        raise APIException.new(
          'Unauthorized',
          _context
        )
      elsif _context.response.status_code == 404
        raise APIException.new(
          'Not Found',
          _context
        )
      end
      validate_response(_context)
      
      # Return appropriate response type.
      decoded = APIHelper.json_deserialize(_context.response.raw_body) unless
        _context.response.raw_body.nil? ||
        _context.response.raw_body.to_s.strip.empty?
      decoded
    end

  end
end
